import { AnatomyMeta } from "@/types/anatomy";

export const anatomies: AnatomyMeta[] = [
  {
    slug: "vps",
    title: "VPS",
    fullTitle: "Anatomie d'un VPS",
    description: "Virtual Private Server — Ta portion de serveur dans le cloud",
    icon: "Server",
    category: "infrastructure",
    layers: [
      {
        id: "silicium-hardware",
        order: 1,
        title: "Silicium & Hardware",
        subtitle: "Le serveur physique dans un datacenter",
        icon: "Cpu",
      },
      {
        id: "hyperviseur",
        order: 2,
        title: "Hyperviseur",
        subtitle: "Le logiciel qui découpe la machine en tranches",
        icon: "Layers",
      },
      {
        id: "machine-virtuelle",
        order: 3,
        title: "Machine Virtuelle",
        subtitle: "Ta portion isolée du serveur",
        icon: "Box",
      },
      {
        id: "systeme-exploitation",
        order: 4,
        title: "Système d'exploitation",
        subtitle: "Linux qui tourne sur ta VM",
        icon: "Monitor",
      },
      {
        id: "reseau-ip",
        order: 5,
        title: "Réseau & IP",
        subtitle: "L'adresse pour atteindre ta machine",
        icon: "Network",
      },
      {
        id: "acces-ssh",
        order: 6,
        title: "Accès SSH",
        subtitle: "La télécommande pour piloter ton VPS",
        icon: "Terminal",
      },
      {
        id: "applications",
        order: 7,
        title: "Applications",
        subtitle: "Ce que tu fais tourner dessus",
        icon: "AppWindow",
      },
    ],
  },
  {
    slug: "terminal",
    title: "Terminal",
    fullTitle: "Anatomie d'un Terminal",
    description: "L'interface texte qui te connecte au coeur de la machine",
    icon: "Terminal",
    category: "infrastructure",
    layers: [
      {
        id: "hardware-io",
        order: 1,
        title: "Hardware (clavier/écran)",
        subtitle: "Les périphériques d'entrée/sortie",
        icon: "Keyboard",
      },
      {
        id: "kernel",
        order: 2,
        title: "Kernel",
        subtitle: "Le noyau qui parle au hardware",
        icon: "Cpu",
      },
      {
        id: "shell",
        order: 3,
        title: "Shell (bash/zsh)",
        subtitle: "L'interpréteur de commandes",
        icon: "ChevronRight",
      },
      {
        id: "environnement",
        order: 4,
        title: "Environnement",
        subtitle: "Variables, PATH, config",
        icon: "Settings",
      },
      {
        id: "commandes",
        order: 5,
        title: "Commandes",
        subtitle: "Les programmes qu'on exécute",
        icon: "Play",
      },
      {
        id: "pipes-redirections",
        order: 6,
        title: "Pipes & Redirections",
        subtitle: "Enchaîner et combiner des commandes",
        icon: "GitBranch",
      },
      {
        id: "emulateur-terminal",
        order: 7,
        title: "Émulateur de terminal",
        subtitle: "L'app graphique (iTerm, Windows Terminal)",
        icon: "AppWindow",
      },
    ],
  },
  {
    slug: "hebergement-web",
    title: "Hébergement Web",
    fullTitle: "Anatomie d'un Hébergement Web",
    description: "Le parcours complet pour mettre un site en ligne",
    icon: "Globe",
    category: "infrastructure",
    layers: [
      {
        id: "serveur-physique",
        order: 1,
        title: "Serveur physique",
        subtitle: "La machine dans le datacenter",
        icon: "Server",
      },
      {
        id: "os-serveur",
        order: 2,
        title: "Système d'exploitation",
        subtitle: "Linux/Windows Server",
        icon: "Monitor",
      },
      {
        id: "serveur-web",
        order: 3,
        title: "Serveur web (Nginx/Apache)",
        subtitle: "Le logiciel qui sert les fichiers",
        icon: "FileServer",
      },
      {
        id: "domaine-dns",
        order: 4,
        title: "Nom de domaine & DNS",
        subtitle: "L'adresse humaine",
        icon: "AtSign",
      },
      {
        id: "certificat-ssl",
        order: 5,
        title: "Certificat SSL",
        subtitle: "Le cadenas HTTPS",
        icon: "Lock",
      },
      {
        id: "fichiers-site",
        order: 6,
        title: "Fichiers du site",
        subtitle: "HTML, CSS, JS, images",
        icon: "FileCode",
      },
      {
        id: "cdn-cache",
        order: 7,
        title: "CDN & Cache",
        subtitle: "Accélération de la livraison",
        icon: "Zap",
      },
      {
        id: "site-en-ligne",
        order: 8,
        title: "Le site en ligne",
        subtitle: "Ce que voit l'utilisateur final",
        icon: "Globe",
      },
    ],
  },
  {
    slug: "serveur",
    title: "Serveur",
    fullTitle: "Anatomie d'un Serveur",
    description: "La machine qui répond à tes demandes, 24h/24",
    icon: "HardDrive",
    category: "infrastructure",
    layers: [
      {
        id: "hardware-serveur",
        order: 1,
        title: "Hardware",
        subtitle: "CPU, RAM, disques, alimentation",
        icon: "Cpu",
      },
      {
        id: "bios-firmware",
        order: 2,
        title: "BIOS/Firmware",
        subtitle: "Le logiciel gravé dans la puce",
        icon: "Chip",
      },
      {
        id: "os",
        order: 3,
        title: "Système d'exploitation",
        subtitle: "Le chef d'orchestre",
        icon: "Monitor",
      },
      {
        id: "services-daemons",
        order: 4,
        title: "Services & Daemons",
        subtitle: "Les programmes qui tournent en permanence",
        icon: "Cog",
      },
      {
        id: "ports-ecoute",
        order: 5,
        title: "Ports & Écoute",
        subtitle: "Les portes d'entrée numériques",
        icon: "DoorOpen",
      },
      {
        id: "requetes-entrantes",
        order: 6,
        title: "Requêtes entrantes",
        subtitle: "Les demandes des clients",
        icon: "ArrowDownToLine",
      },
      {
        id: "reponses",
        order: 7,
        title: "Réponses",
        subtitle: "Ce que le serveur renvoie",
        icon: "ArrowUpFromLine",
      },
    ],
  },
  {
    slug: "requete-http",
    title: "Requête HTTP",
    fullTitle: "Anatomie d'une Requête HTTP",
    description: "Le voyage d'un clic jusqu'à la réponse du serveur",
    icon: "ArrowRightLeft",
    category: "reseau",
    layers: [
      {
        id: "client-navigateur",
        order: 1,
        title: "Client (navigateur)",
        subtitle: "L'utilisateur qui clique",
        icon: "Monitor",
      },
      {
        id: "resolution-dns",
        order: 2,
        title: "Résolution DNS",
        subtitle: "Trouver l'adresse IP du serveur",
        icon: "Search",
      },
      {
        id: "connexion-tcp",
        order: 3,
        title: "Connexion TCP",
        subtitle: "Établir le canal de communication",
        icon: "Cable",
      },
      {
        id: "handshake-tls",
        order: 4,
        title: "Handshake TLS",
        subtitle: "Sécuriser le canal (HTTPS)",
        icon: "Lock",
      },
      {
        id: "requete-http",
        order: 5,
        title: "Requête HTTP",
        subtitle: "Méthode + URL + headers + body",
        icon: "Send",
      },
      {
        id: "traitement-serveur",
        order: 6,
        title: "Traitement serveur",
        subtitle: "Le serveur lit et traite la demande",
        icon: "Cog",
      },
      {
        id: "reponse-http",
        order: 7,
        title: "Réponse HTTP",
        subtitle: "Status code + headers + body",
        icon: "FileDown",
      },
      {
        id: "rendu-navigateur",
        order: 8,
        title: "Rendu navigateur",
        subtitle: "Afficher le résultat à l'écran",
        icon: "Eye",
      },
    ],
  },
  {
    slug: "api",
    title: "API",
    fullTitle: "Anatomie d'une API",
    description: "Le contrat entre deux logiciels qui veulent se parler",
    icon: "Plug",
    category: "reseau",
    layers: [
      {
        id: "donnees-brutes",
        order: 1,
        title: "Données brutes",
        subtitle: "L'information stockée (BDD, fichiers)",
        icon: "Database",
      },
      {
        id: "logique-metier",
        order: 2,
        title: "Logique métier",
        subtitle: "Les règles de traitement",
        icon: "Cog",
      },
      {
        id: "endpoints-routes",
        order: 3,
        title: "Endpoints / Routes",
        subtitle: "Les URLs d'accès",
        icon: "Route",
      },
      {
        id: "methodes-http",
        order: 4,
        title: "Méthodes HTTP",
        subtitle: "GET, POST, PUT, DELETE",
        icon: "ArrowRightLeft",
      },
      {
        id: "format-donnees",
        order: 5,
        title: "Format de données",
        subtitle: "JSON, XML (le langage commun)",
        icon: "Braces",
      },
      {
        id: "authentification-api",
        order: 6,
        title: "Authentification",
        subtitle: "Qui a le droit d'appeler",
        icon: "KeyRound",
      },
      {
        id: "documentation",
        order: 7,
        title: "Documentation",
        subtitle: "Le mode d'emploi (Swagger, OpenAPI)",
        icon: "BookOpen",
      },
      {
        id: "consommateur",
        order: 8,
        title: "Consommateur",
        subtitle: "L'app ou le service qui utilise l'API",
        icon: "AppWindow",
      },
    ],
  },
  {
    slug: "dns",
    title: "DNS",
    fullTitle: "Anatomie du DNS",
    description: "Le GPS d'Internet qui transforme les noms en adresses",
    icon: "MapPin",
    category: "reseau",
    layers: [
      {
        id: "nom-domaine-achete",
        order: 1,
        title: "Nom de domaine acheté",
        subtitle: "Le nom lisible (monsite.com)",
        icon: "Tag",
      },
      {
        id: "registrar",
        order: 2,
        title: "Registrar",
        subtitle: "Le vendeur de noms (OVH, Namecheap)",
        icon: "Store",
      },
      {
        id: "serveurs-dns-racine",
        order: 3,
        title: "Serveurs DNS racine",
        subtitle: "L'annuaire mondial",
        icon: "Globe",
      },
      {
        id: "serveurs-tld",
        order: 4,
        title: "Serveurs TLD",
        subtitle: "Les responsables du .com, .fr, .io",
        icon: "Network",
      },
      {
        id: "serveur-dns-autoritaire",
        order: 5,
        title: "Serveur DNS autoritaire",
        subtitle: "Celui qui connaît TON domaine",
        icon: "Server",
      },
      {
        id: "enregistrements-dns",
        order: 6,
        title: "Enregistrements DNS",
        subtitle: "A, CNAME, MX, TXT (les lignes du carnet)",
        icon: "List",
      },
      {
        id: "resolver-cache",
        order: 7,
        title: "Resolver / Cache",
        subtitle: "Le cache local qui accélère",
        icon: "Zap",
      },
      {
        id: "resolution-finale",
        order: 8,
        title: "Résolution finale",
        subtitle: "Le navigateur obtient l'IP",
        icon: "CheckCircle",
      },
    ],
  },
  {
    slug: "nom-de-domaine",
    title: "Nom de Domaine",
    fullTitle: "Anatomie d'un Nom de Domaine",
    description: "L'adresse lisible qui remplace les chiffres",
    icon: "AtSign",
    category: "reseau",
    layers: [
      {
        id: "adresse-ip",
        order: 1,
        title: "Adresse IP",
        subtitle: "L'adresse numérique réelle",
        icon: "Hash",
      },
      {
        id: "besoin-nom-lisible",
        order: 2,
        title: "Besoin d'un nom lisible",
        subtitle: "Pourquoi les humains ont besoin de noms",
        icon: "User",
      },
      {
        id: "structure-nom",
        order: 3,
        title: "Structure du nom",
        subtitle: "sous-domaine.domaine.TLD",
        icon: "Layers",
      },
      {
        id: "registrar-domaine",
        order: 4,
        title: "Registrar",
        subtitle: "Le bureau d'enregistrement",
        icon: "Store",
      },
      {
        id: "whois",
        order: 5,
        title: "WHOIS",
        subtitle: "L'annuaire des propriétaires",
        icon: "Search",
      },
      {
        id: "config-dns",
        order: 6,
        title: "Configuration DNS",
        subtitle: "Pointer le nom vers une IP",
        icon: "Settings",
      },
      {
        id: "propagation",
        order: 7,
        title: "Propagation",
        subtitle: "Le temps que l'info se répande",
        icon: "Timer",
      },
      {
        id: "nom-en-action",
        order: 8,
        title: "Le nom en action",
        subtitle: "Taper l'URL et arriver sur le site",
        icon: "Globe",
      },
    ],
  },
  {
    slug: "docker",
    title: "Docker",
    fullTitle: "Anatomie de Docker",
    description: "La boîte magique qui empaquète tes apps",
    icon: "Container",
    category: "developpement",
    layers: [
      {
        id: "hardware-docker",
        order: 1,
        title: "Hardware du serveur",
        subtitle: "La machine physique",
        icon: "Server",
      },
      {
        id: "os-hote",
        order: 2,
        title: "Système d'exploitation hôte",
        subtitle: "Linux sur la machine",
        icon: "Monitor",
      },
      {
        id: "docker-engine",
        order: 3,
        title: "Docker Engine",
        subtitle: "Le moteur qui gère les conteneurs",
        icon: "Cog",
      },
      {
        id: "image-docker",
        order: 4,
        title: "Image Docker",
        subtitle: "Le moule/la recette (Dockerfile)",
        icon: "FileCode",
      },
      {
        id: "conteneur",
        order: 5,
        title: "Conteneur",
        subtitle: "L'instance qui tourne",
        icon: "Box",
      },
      {
        id: "volumes-reseaux",
        order: 6,
        title: "Volumes & Réseaux",
        subtitle: "Persistance des données et communication",
        icon: "HardDrive",
      },
      {
        id: "docker-compose",
        order: 7,
        title: "Docker Compose",
        subtitle: "Orchestrer plusieurs conteneurs ensemble",
        icon: "GitMerge",
      },
      {
        id: "app-deployee",
        order: 8,
        title: "Application déployée",
        subtitle: "Le service accessible",
        icon: "Rocket",
      },
    ],
  },
  {
    slug: "git-versioning",
    title: "Git & Versioning",
    fullTitle: "Anatomie de Git & Versioning",
    description: "La machine à remonter le temps de ton code",
    icon: "GitBranch",
    category: "developpement",
    layers: [
      {
        id: "fichiers-disque",
        order: 1,
        title: "Fichiers sur un disque",
        subtitle: "Le point de départ",
        icon: "File",
      },
      {
        id: "snapshots-commits",
        order: 2,
        title: "Snapshots (commits)",
        subtitle: "Photographier l'état du projet",
        icon: "Camera",
      },
      {
        id: "arbre-commits",
        order: 3,
        title: "Arbre de commits",
        subtitle: "L'historique linéaire",
        icon: "GitCommitHorizontal",
      },
      {
        id: "branches",
        order: 4,
        title: "Branches",
        subtitle: "Les univers parallèles",
        icon: "GitBranch",
      },
      {
        id: "merge-rebase",
        order: 5,
        title: "Merge & Rebase",
        subtitle: "Réunir les univers",
        icon: "GitMerge",
      },
      {
        id: "remote-github",
        order: 6,
        title: "Remote (GitHub)",
        subtitle: "La copie dans le cloud",
        icon: "Cloud",
      },
      {
        id: "push-pull",
        order: 7,
        title: "Push / Pull",
        subtitle: "Synchroniser local et remote",
        icon: "RefreshCw",
      },
      {
        id: "collaboration",
        order: 8,
        title: "Collaboration",
        subtitle: "PRs, reviews, issues",
        icon: "Users",
      },
    ],
  },
  {
    slug: "json",
    title: "JSON",
    fullTitle: "Anatomie du JSON",
    description: "Le langage universel que parlent toutes les machines",
    icon: "Braces",
    category: "developpement",
    layers: [
      {
        id: "bits-octets",
        order: 1,
        title: "Bits & Octets",
        subtitle: "Comment un ordinateur stocke l'information",
        icon: "Binary",
      },
      {
        id: "texte-brut",
        order: 2,
        title: "Texte brut (string)",
        subtitle: "Du texte sans structure",
        icon: "Type",
      },
      {
        id: "paires-cle-valeur",
        order: 3,
        title: "Paires clé-valeur",
        subtitle: "Le concept fondamental de JSON",
        icon: "KeyRound",
      },
      {
        id: "types-donnees",
        order: 4,
        title: "Types de données",
        subtitle: "String, number, boolean, null, array, object",
        icon: "List",
      },
      {
        id: "imbrication",
        order: 5,
        title: "Imbrication",
        subtitle: "Des objets dans des objets",
        icon: "Layers",
      },
      {
        id: "serialisation-parsing",
        order: 6,
        title: "Sérialisation / Parsing",
        subtitle: "Texte vers objet et retour",
        icon: "RefreshCw",
      },
      {
        id: "json-apis",
        order: 7,
        title: "JSON dans les APIs",
        subtitle: "Le format universel du web",
        icon: "Globe",
      },
      {
        id: "json-quotidien",
        order: 8,
        title: "JSON au quotidien",
        subtitle: "Config files, package.json, n8n",
        icon: "FileJson",
      },
    ],
  },
  {
    slug: "process-linux",
    title: "Process Linux",
    fullTitle: "Anatomie d'un Process Linux",
    description: "La vie d'un programme qui tourne sur ta machine",
    icon: "Activity",
    category: "infrastructure",
    layers: [
      {
        id: "programme-disque",
        order: 1,
        title: "Programme sur le disque",
        subtitle: "Le fichier exécutable",
        icon: "File",
      },
      {
        id: "chargement-memoire",
        order: 2,
        title: "Chargement en mémoire",
        subtitle: "Le programme devient process",
        icon: "MemoryStick",
      },
      {
        id: "pid",
        order: 3,
        title: "PID",
        subtitle: "Le numéro d'identité du process",
        icon: "Hash",
      },
      {
        id: "etats-process",
        order: 4,
        title: "États du process",
        subtitle: "Running, sleeping, stopped, zombie",
        icon: "Activity",
      },
      {
        id: "arbre-processus",
        order: 5,
        title: "Arbre de processus",
        subtitle: "Parent, enfants, init/systemd",
        icon: "GitBranch",
      },
      {
        id: "signaux",
        order: 6,
        title: "Signaux",
        subtitle: "Les messages entre processes (SIGTERM, SIGKILL)",
        icon: "Bell",
      },
      {
        id: "ressources",
        order: 7,
        title: "Ressources",
        subtitle: "CPU, RAM, I/O consommés",
        icon: "Gauge",
      },
      {
        id: "outils-monitoring",
        order: 8,
        title: "Outils de monitoring",
        subtitle: "top, htop, ps, systemctl",
        icon: "Monitor",
      },
    ],
  },
  {
    slug: "authentification",
    title: "Authentification",
    fullTitle: "Anatomie de l'Authentification",
    description: "Comment prouver que tu es bien toi sur Internet",
    icon: "ShieldCheck",
    category: "securite",
    layers: [
      {
        id: "identite",
        order: 1,
        title: "Identité",
        subtitle: "Qui es-tu ? (email, username)",
        icon: "User",
      },
      {
        id: "credential",
        order: 2,
        title: "Credential",
        subtitle: "Comment le prouves-tu ? (password, clé)",
        icon: "KeyRound",
      },
      {
        id: "hachage",
        order: 3,
        title: "Hachage",
        subtitle: "Stocker le mot de passe sans le stocker (bcrypt)",
        icon: "Hash",
      },
      {
        id: "verification",
        order: 4,
        title: "Vérification",
        subtitle: "Comparer le hash",
        icon: "CheckCircle",
      },
      {
        id: "session-token",
        order: 5,
        title: "Session / Token",
        subtitle: "Le bracelet du festival (JWT, cookie)",
        icon: "Ticket",
      },
      {
        id: "autorisation",
        order: 6,
        title: "Autorisation",
        subtitle: "Qu'as-tu le droit de faire ? (roles, permissions)",
        icon: "Shield",
      },
      {
        id: "oauth-sso",
        order: 7,
        title: "OAuth / SSO",
        subtitle: "Se connecter via Google, GitHub",
        icon: "LogIn",
      },
      {
        id: "flux-complet",
        order: 8,
        title: "Flux complet",
        subtitle: "Login, accès, refresh, logout",
        icon: "RefreshCw",
      },
    ],
  },
  {
    slug: "certificat-ssl-tls",
    title: "Certificat SSL/TLS",
    fullTitle: "Anatomie d'un Certificat SSL/TLS",
    description: "Le cadenas qui protège tes données sur le web",
    icon: "Lock",
    category: "securite",
    layers: [
      {
        id: "texte-en-clair",
        order: 1,
        title: "Texte en clair",
        subtitle: "Les données non protégées",
        icon: "FileText",
      },
      {
        id: "chiffrement-symetrique",
        order: 2,
        title: "Chiffrement symétrique",
        subtitle: "Une seule clé pour chiffrer/déchiffrer",
        icon: "KeyRound",
      },
      {
        id: "chiffrement-asymetrique",
        order: 3,
        title: "Chiffrement asymétrique",
        subtitle: "Clé publique + clé privée",
        icon: "KeySquare",
      },
      {
        id: "autorite-certification",
        order: 4,
        title: "Autorité de certification (CA)",
        subtitle: "Le notaire du web",
        icon: "BadgeCheck",
      },
      {
        id: "certificat-ssl",
        order: 5,
        title: "Certificat SSL",
        subtitle: "La carte d'identité du site",
        icon: "FileCheck",
      },
      {
        id: "handshake-tls",
        order: 6,
        title: "Handshake TLS",
        subtitle: "La poignée de main sécurisée",
        icon: "Handshake",
      },
      {
        id: "https",
        order: 7,
        title: "HTTPS",
        subtitle: "HTTP + la couche de sécurité",
        icon: "ShieldCheck",
      },
      {
        id: "cadenas-vert",
        order: 8,
        title: "Cadenas vert",
        subtitle: "Ce que voit l'utilisateur",
        icon: "Lock",
      },
    ],
  },
  {
    slug: "base-de-donnees",
    title: "Base de Données",
    fullTitle: "Anatomie d'une Base de Données",
    description: "L'entrepôt organisé où vivent tes données",
    icon: "Database",
    category: "donnees",
    layers: [
      {
        id: "disque-stockage",
        order: 1,
        title: "Disque dur / Stockage",
        subtitle: "Où les données sont physiquement écrites",
        icon: "HardDrive",
      },
      {
        id: "moteur-stockage",
        order: 2,
        title: "Moteur de stockage",
        subtitle: "Comment les données sont organisées sur le disque",
        icon: "Cog",
      },
      {
        id: "schema-tables",
        order: 3,
        title: "Schéma & Tables",
        subtitle: "La structure (colonnes, types, relations)",
        icon: "Table",
      },
      {
        id: "index",
        order: 4,
        title: "Index",
        subtitle: "Les raccourcis pour chercher vite",
        icon: "Search",
      },
      {
        id: "langage-sql",
        order: 5,
        title: "Langage SQL",
        subtitle: "Le langage pour parler à la base",
        icon: "Code",
      },
      {
        id: "connexion-auth",
        order: 6,
        title: "Connexion & Auth",
        subtitle: "Qui a le droit de lire/écrire",
        icon: "Lock",
      },
      {
        id: "orm-client",
        order: 7,
        title: "ORM / Client",
        subtitle: "L'intermédiaire (Prisma, Supabase JS)",
        icon: "Plug",
      },
      {
        id: "application-bdd",
        order: 8,
        title: "Application",
        subtitle: "L'interface qui affiche les données",
        icon: "AppWindow",
      },
    ],
  },
  {
    slug: "workflow-n8n",
    title: "Workflow n8n",
    fullTitle: "Anatomie d'un Workflow",
    description: "L'automate qui enchaîne les actions à ta place",
    icon: "Workflow",
    category: "automatisation",
    layers: [
      {
        id: "trigger-declencheur",
        order: 1,
        title: "Trigger / Déclencheur",
        subtitle: "L'événement qui démarre le workflow",
        icon: "Zap",
      },
      {
        id: "donnees-entree",
        order: 2,
        title: "Données d'entrée",
        subtitle: "Les informations reçues (JSON)",
        icon: "FileJson",
      },
      {
        id: "noeuds-traitement",
        order: 3,
        title: "Noeuds de traitement",
        subtitle: "Transformer, filtrer, enrichir",
        icon: "Cog",
      },
      {
        id: "connexions-api",
        order: 4,
        title: "Connexions API",
        subtitle: "Appeler des services externes",
        icon: "Plug",
      },
      {
        id: "conditions-branches",
        order: 5,
        title: "Conditions & Branches",
        subtitle: "Logique if/else, switch",
        icon: "GitBranch",
      },
      {
        id: "noeuds-sortie",
        order: 6,
        title: "Noeuds de sortie",
        subtitle: "Envoyer le résultat (email, BDD, webhook)",
        icon: "Send",
      },
      {
        id: "gestion-erreurs",
        order: 7,
        title: "Gestion d'erreurs",
        subtitle: "Que faire quand ça plante",
        icon: "AlertTriangle",
      },
      {
        id: "execution-logs",
        order: 8,
        title: "Exécution & Logs",
        subtitle: "Suivi et historique",
        icon: "ScrollText",
      },
    ],
  },
];

export function getAnatomyBySlug(slug: string): AnatomyMeta | undefined {
  return anatomies.find((a) => a.slug === slug);
}

export function getAnatomiesByCategory() {
  const grouped = new Map<string, AnatomyMeta[]>();
  for (const anatomy of anatomies) {
    const existing = grouped.get(anatomy.category) || [];
    existing.push(anatomy);
    grouped.set(anatomy.category, existing);
  }
  return grouped;
}
